[build]
  publish = "public" # Replace "public" with your actual build output directory
  functions = "functions"

# Allow direct access to static files in the views directory
[[redirects]]
  from = "/"
  to = "/views/usage.html"
  status = 200
  
[[redirects]]
  from = "/views/*"
  to = "/views/:splat"
  status = 200

# Allow direct access to images
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Redirect all other requests to the serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

